import Foundation

/// Unified access rules for DayCast Free vs Pro.
@MainActor
enum EntitlementChecker {
  static let freeSavedLocationLimit = 1

  static func access(
    subscription: SubscriptionManager,
    hasDeveloperKey: Bool
  ) -> GrokAccessTier {
    GrokAccessRules.tier(
      isPro: subscription.isPro,
      proxyConfigured: GrokProxyConfiguration.isConfigured,
      hasDeveloperKey: hasDeveloperKey
    ) ?? .free
  }

  static func canUseGrokAI(
    subscription: SubscriptionManager,
    hasDeveloperKey: Bool
  ) -> Bool {
    GrokAccessRules.canUseGrokAI(
      isPro: subscription.isPro,
      proxyConfigured: GrokProxyConfiguration.isConfigured,
      hasDeveloperKey: hasDeveloperKey
    )
  }

  /// The morning brief is a scheduled Grok call, so it needs the same access.
  static func canUseMorningBrief(
    subscription: SubscriptionManager,
    hasDeveloperKey: Bool
  ) -> Bool {
    GrokAccessRules.canUseMorningBrief(
      isPro: subscription.isPro,
      proxyConfigured: GrokProxyConfiguration.isConfigured,
      hasDeveloperKey: hasDeveloperKey
    )
  }

  static func canUseRadarFuture(
    subscription: SubscriptionManager
  ) -> Bool {
    subscription.isPro
  }

  static func canUseLiveActivity(
    subscription: SubscriptionManager
  ) -> Bool {
    subscription.isPro
  }

  /// Widget AI one-liner is generated by Grok, and the widget itself is Pro-only.
  static func canUseWidgetGrokBrief(
    subscription: SubscriptionManager,
    hasDeveloperKey: Bool
  ) -> Bool {
    GrokAccessRules.canUseWidgetGrokBrief(
      isPro: subscription.isPro,
      proxyConfigured: GrokProxyConfiguration.isConfigured,
      hasDeveloperKey: hasDeveloperKey
    )
  }

  static func maxSavedLocations(
    subscription: SubscriptionManager
  ) -> Int? {
    subscription.isPro ? nil : freeSavedLocationLimit
  }

  static func canAddLocation(
    currentCount: Int,
    subscription: SubscriptionManager
  ) -> Bool {
    guard let limit = maxSavedLocations(subscription: subscription) else { return true }
    return currentCount < limit
  }
}

enum GrokAccessTier: Equatable {
  case free
  case pro
  case developerKey
}
