#!/usr/bin/env bash
# Builds a throwaway certificate chain that mirrors Apple's shape:
#   root (P-384, self-signed) -> intermediate (P-384) -> leaf (P-256, ES256)
#
# Plus a second, unrelated root so tests can prove an untrusted chain is
# rejected. Nothing here touches Apple's real root — these are test keys only.
#
# Regenerate with: npm run fixtures

set -euo pipefail
cd "$(dirname "$0")"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

cat >"$WORK/ca.cnf" <<'EOF'
basicConstraints = critical,CA:TRUE
keyUsage = critical,keyCertSign,cRLSign
EOF

cat >"$WORK/leaf.cnf" <<'EOF'
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature
EOF

make_root() {
  local name="$1" subject="$2"
  openssl ecparam -name secp384r1 -genkey -noout -out "$WORK/$name.key" 2>/dev/null
  openssl req -new -x509 -sha384 -key "$WORK/$name.key" -out "$WORK/$name.crt" \
    -days 3650 -subj "$subject" -extensions v3_ca -config <(
      cat /etc/ssl/openssl.cnf 2>/dev/null || echo "[req]"
      echo "[v3_ca]"
      cat "$WORK/ca.cnf"
    ) 2>/dev/null
}

make_root root "/CN=SpotterCast Test Root/O=SpotterCast Tests"
make_root rogue "/CN=SpotterCast Rogue Root/O=SpotterCast Tests"

# Intermediate, signed by the trusted root.
openssl ecparam -name secp384r1 -genkey -noout -out "$WORK/intermediate.key" 2>/dev/null
openssl req -new -sha384 -key "$WORK/intermediate.key" -out "$WORK/intermediate.csr" \
  -subj "/CN=SpotterCast Test Intermediate/O=SpotterCast Tests" 2>/dev/null
openssl x509 -req -sha384 -in "$WORK/intermediate.csr" \
  -CA "$WORK/root.crt" -CAkey "$WORK/root.key" -CAcreateserial \
  -out "$WORK/intermediate.crt" -days 3650 -extfile "$WORK/ca.cnf" 2>/dev/null

# Leaf on P-256 / ES256, matching what Apple signs transactions with.
make_leaf() {
  local name="$1" ca="$2"
  openssl ecparam -name prime256v1 -genkey -noout -out "$WORK/$name.key" 2>/dev/null
  openssl req -new -sha256 -key "$WORK/$name.key" -out "$WORK/$name.csr" \
    -subj "/CN=SpotterCast Test Leaf/O=SpotterCast Tests" 2>/dev/null
  openssl x509 -req -sha256 -in "$WORK/$name.csr" \
    -CA "$WORK/$ca.crt" -CAkey "$WORK/$ca.key" -CAcreateserial \
    -out "$WORK/$name.crt" -days 3650 -extfile "$WORK/leaf.cnf" 2>/dev/null
  openssl pkcs8 -topk8 -nocrypt -in "$WORK/$name.key" -out "$WORK/$name.pkcs8.der" -outform DER 2>/dev/null
}

make_leaf leaf intermediate
make_leaf rogueLeaf rogue

der_b64() { openssl x509 -in "$1" -outform DER 2>/dev/null | base64 | tr -d '\n'; }
raw_b64() { base64 <"$1" | tr -d '\n'; }

cat >fixtures.json <<EOF
{
  "_comment": "Generated by test/fixtures/generate.sh — test keys only, never real credentials.",
  "root": "$(der_b64 "$WORK/root.crt")",
  "intermediate": "$(der_b64 "$WORK/intermediate.crt")",
  "leaf": "$(der_b64 "$WORK/leaf.crt")",
  "leafPrivateKey": "$(raw_b64 "$WORK/leaf.pkcs8.der")",
  "rogueRoot": "$(der_b64 "$WORK/rogue.crt")",
  "rogueLeaf": "$(der_b64 "$WORK/rogueLeaf.crt")",
  "rogueLeafPrivateKey": "$(raw_b64 "$WORK/rogueLeaf.pkcs8.der")"
}
EOF

echo "wrote $(pwd)/fixtures.json"
